name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin 320060061347.dkr.ecr.us-east-1.amazonaws.com/resume

      - name: Build and push Docker image to ECR
        run: |
          docker build -t your-repository-name:latest .
          docker tag resume:latest 320060061347.dkr.ecr.us-east-1.amazonaws.com/resume:latest
          docker push 320060061347.dkr.ecr.us-east-1.amazonaws.com/resume:latest